# Getting Started with ndarray


**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.


## How to create Rank 1 numpy arrays

In [2]:
import numpy as np
an_array = np.array([3, 33, 333]) 
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2] )

3 33 333


In [5]:
an_array[0] = 888
print(an_array)

[888  33 333]


## How to create a Rank 2 numpy array

A rank 2 **ndarray** is one with two dimensions. Notice the format below of [[row], [row]]. 2 dimensional arrays are great for representing matrices which are often useful in data science.

In [6]:
another = np.array([[11,12,13],[21,22,23]])
print(another)
print("The shape is 2 rows, 3 columns: ", another.shape)
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0,0],another[0,1], another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 12 21


## There are many ways to create numpy arrays: 
Here we create a number of different size arrays with different shapes and different pre-filled values. numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [8]:
import numpy as np
ex1 = np.zeros((2,2))
print(ex1)


[[ 0.  0.]
 [ 0.  0.]]


In [9]:
ex2 = np.full((2,2), 9.0)
print(ex2)

[[ 9.  9.]
 [ 9.  9.]]


In [10]:
ex3 = np.eye(2,2)
print(ex3)

[[ 1.  0.]
 [ 0.  1.]]


In [11]:
ex4 = np.ones((1,2))
print(ex4)

[[ 1.  1.]]


In [12]:
print(ex4.shape)
print()
print(ex4[0,1])

(1, 2)

1.0


In [13]:
ex5 = np.random.random((2,2))
print(ex5)

[[ 0.22267175  0.29707623]
 [ 0.25171621  0.66427813]]


# Array Indexing

## Slice Indexing: 
Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out subregions of ndarrays

In [15]:
import numpy as np
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


use array to get a subarray of the first 2 rows x 2 columns

In [16]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array

In [17]:
print("Before:", an_array[0, 1]) #inspect the element at 0, 1
a_slice[0, 0] = 1000  # a_slice[0, 0] is the same piece of data as an_array [0, 1]
print("After", an_array[0, 1])

Before: 12
After 1000


## Use both integer & slice indexing
We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [18]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [19]:
row_rank1 = an_array[1, : ]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [20]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [21]:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


## Array Indexing for changing elements:
Sometimes it's useful to use an aray of indexes to access or change elements

In [22]:
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [23]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indinces picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indinces picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [28]:
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [29]:
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [30]:
an_array[row_indices, col_indices] += 100000
print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]
